trigger:
  branches:
    include:
      - main  # Trigger deployment on main branch commits

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'  # Adjust based on your web app's runtime


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)' 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'
    replaceExistingArchive: true

- upload: '$(Build.ArtifactStagingDirectory)/webapp.zip'
  artifact: drop

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'sandbox-sc'
    appName: 'MyWebAppg'
    package: '$(Build.ArtifactStagingDirectory)/webapp.zip'
